### ISSUE TITLE
Gadi install error

### ISSUE THREAD

**Issue by bknight1** [underworldcode/UWGeodynamics#156]
Hi @rbeucher 

I've managed to install UW on Raijin using the install guide on the v29 branch, however I cannot get the UWGeodynamics module imported. I've installed via pip3 `pip3 install git+https://github.com/underworldcode/uwgeodynamics` however when I import the module I get the following error:

```
>>> import UWGeodynamics
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/565/bk2562/.local/lib/python3.7/site-packages/UWGeodynamics/__init__.py", line 30, in <module>
    import glucifer
ModuleNotFoundError: No module named 'glucifer'
```

Cheers

**Comment by julesghub** [comment]
Hi @bknight1, we are actively working on the v29 tag now, it needs updating. We aim to have this done by the end of this week. Included in this will be a new set of install instruction for gadi. 
I will keep you posted on this ticket.

**Comment by bknight1** [comment]
Thanks @julesghub  I'll keep an eye out for updates too

**Comment by bknight1** [comment]
Hi @julesghub, has there been any updates? I'm still running into the same issue with UWGeodynamics

**Comment by bknight1** [comment]
Hi @julesghub  and @rbeucher,

If I remove the glucifer check, I get the following error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/565/bk2562/.local/lib/python3.7/site-packages/UWGeodynamics/__init__.py", line 44, in <module>
    from .LecodeIsostasy import LecodeIsostasy
  File "/home/565/bk2562/.local/lib/python3.7/site-packages/UWGeodynamics/LecodeIsostasy/__init__.py", line 2, in <module>
    from .LecodeIsostasy import LecodeIsostasy
  File "/home/565/bk2562/.local/lib/python3.7/site-packages/UWGeodynamics/LecodeIsostasy/LecodeIsostasy.py", line 6, in <module>
    from UWGeodynamics._material import Material
  File "/home/565/bk2562/.local/lib/python3.7/site-packages/UWGeodynamics/_material.py", line 24, in <module>
    class Material(object):
  File "/home/565/bk2562/.local/lib/python3.7/site-packages/UWGeodynamics/_material.py", line 43, in Material
    viscosityChangeX2=0.3, viscosityChange=1.0):
  File "/home/565/bk2562/.local/lib/python3.7/site-packages/pint/registry_helpers.py", line 329, in decorator
    % (func.__name__, count_params, len(dimensions))
TypeError: __init__ takes 24 parameters, but 1 dimensions were passed
```

**Comment by bknight1** [comment]
Saw the update to use pint v0.9, and appears to work. Will close this for now.

**Comment by julesghub** [comment]
Great it worked for you @bknight1!
