### ISSUE TITLE
checkpoint interval problems on Gadi

### ISSUE THREAD

**Issue by HanyMKhalil** [underworldcode/UWGeodynamics#200]
Hi All, I just encounter a weird problem recently.

I was able to run models before and save outputs by checkpoint interval

Now I tried to run some models they run fine without adding checkpoint interval (so I do not save any outputs), but when I add checkpoint interval the models stops and couldn't save any output.

I get this message in error output file:

Loading python3/3.7.4
  Loading requirement: intel-mkl/2019.3.199
An uncaught exception appears to have been raised by all processes. Set the 'UW_ALL_MESSAGES' environment variable to see all messages. Rank 0 message is:
Traceback (most recent call last):
  File "/home/565/hk2371/q4_2020_jobs/models_3/3D-ortho-test.py", line 253, in <module>
    Model.run_for(20.0 * u.megayear, checkpoint_interval= 4.0 * u.megayear)
  File "/home/565/hk2371/.local/lib/python3.7/site-packages/UWGeodynamics/_model.py", line 1576, in run_for
    checkpoint_times, restart_checkpoint, output_dt_units)
  File "/home/565/hk2371/.local/lib/python3.7/site-packages/UWGeodynamics/_model.py", line 2296, in __init__
    self.checkpoint_all()
  File "/home/565/hk2371/.local/lib/python3.7/site-packages/UWGeodynamics/_model.py", line 2375, in checkpoint_all
    self.checkpoint_fields(variables, checkpointID, time, outputDir)
  File "/home/565/hk2371/.local/lib/python3.7/site-packages/UWGeodynamics/_model.py", line 2419, in checkpoint_fields
    time=time)
  File "/home/565/hk2371/.local/lib/python3.7/site-packages/UWGeodynamics/Underworld_extended/_mesh.py", line 142, in save
    dset[self.data_nodegId[0:local],:] = self.data[0:local] * fact
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/home/565/hk2371/.local/lib/python3.7/site-packages/h5py/_hl/dataset.py", line 708, in __setitem__
    self.id.write(mspace, fspace, val, mtype, dxpl=self._dxpl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5d.pyx", line 222, in h5py.h5d.DatasetID.write
  File "h5py/_proxy.pyx", line 132, in h5py._proxy.dset_rw
  File "h5py/_proxy.pyx", line 93, in h5py._proxy.H5PY_H5Dwrite
OSError: Can't write data (MPI_ERR_IO: input/output error)
--------------------------------------------------------------------------
MPI_ABORT was invoked on rank 194 in communicator MPI COMMUNICATOR 3 DUP FROM 0
with errorcode 1.

NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
You may or may not see output from other processes, depending on
exactly when Open MPI kills them.
--------------------------------------------------------------------------
[31]PETSC ERROR: ------------------------------------------------------------------------
[31]PETSC ERROR: Caught signal number 15 Terminate: Some process (or the batch system) has told this process to end
[31]PETSC ERROR: Try option -start_in_debugger or -on_error_attach_debugger
[31]PETSC ERROR: or see https://www.mcs.anl.gov/petsc/documentation/faq.html#valgrind
[31]PETSC ERROR: or try http://valgrind.org on GNU/linux and Apple Mac OS X to find memory corruption errors
"3D-ortho-test.pbs.e12417452" 456L, 51616C

**Comment by HanyMKhalil** [comment]
here is my code it runs fine without having checkpoint interval:

#!/usr/bin/env python
# coding: utf-8

# In[ ]:


import UWGeodynamics as GEO
from underworld import function as fn
import numpy as np
import math


# In[ ]:


u = GEO.UnitRegistry


# In[ ]:


# Characteristic values of the system
half_rate = 0.64 * u.centimeter / u.year
model_length = 256e3 * u.meter
surfaceTemp = 293.15 * u.degK
baseModelTemp = 1393.15 * u.degK
bodyforce = 3300 * u.kilogram / u.metre**3 * 9.81 * u.meter / u.second**2

KL = model_length
Kt = KL / half_rate
KM = bodyforce * KL**2 * Kt**2
KT = (baseModelTemp - surfaceTemp)

GEO.scaling_coefficients["[length]"] = KL
GEO.scaling_coefficients["[time]"] = Kt
GEO.scaling_coefficients["[mass]"]= KM
GEO.scaling_coefficients["[temperature]"] = KT


# In[ ]:


Model = GEO.Model(elementRes=(64, 128, 32), 
                  minCoord=(-128. * u.kilometer, 0. * u.kilometer, -120. * u.kilometer), 
                  maxCoord=(128. * u.kilometer, 512. * u.kilometer, 8. * u.kilometer), 
                  gravity=(0.0, 0.0, -9.81 * u.meter / u.second**2))


# In[ ]:


Model.minViscosity = 1e18 * u.pascal * u.second
Model.maxViscosity = 1e25 * u.pascal * u.second


# In[ ]:


Model.outputDir="/scratch/n69/hk2371/3D-ortho-test"


# In[ ]:


Model.diffusivity = 1e-6 * u.metre**2 / u.second 
Model.capacity    = 1000. * u.joule / (u.kelvin * u.kilogram)


# In[ ]:


air        = Model.add_material(name="Air", shape=GEO.shapes.Layer(top=Model.top, bottom=0 * u.kilometer))
uppercrust = Model.add_material(name="UppperCrust", shape=GEO.shapes.Layer(top=air.bottom, bottom=-20 * u.kilometer))
lowercrust = Model.add_material(name="LowerCrust", shape=GEO.shapes.Layer(top=uppercrust.bottom, bottom=-35 * u.kilometer))
mantleLithosphere = Model.add_material(name="MantleLithosphere", shape=GEO.shapes.Layer(top=lowercrust.bottom, bottom=-90 * u.kilometer))
mantle     = Model.add_material(name="Mantle", shape=GEO.shapes.Layer(top=mantleLithosphere.bottom, bottom=Model.bottom))


# In[ ]:


air.diffusivity = 1.0e-6 * u.metre**2 / u.second
air.capacity = 100. * u.joule / (u.kelvin * u.kilogram)


# In[ ]:


air.density         = 1. * u.kilogram / u.metre**3
uppercrust.density  = GEO.LinearDensity(reference_density=2700. * u.kilogram / u.metre**3)
lowercrust.density  = GEO.LinearDensity(reference_density=2900. * u.kilogram / u.metre**3)
mantleLithosphere.density  = GEO.LinearDensity(reference_density=3300. * u.kilogram / u.metre**3)
mantle.density      = GEO.LinearDensity(reference_density=3300. * u.kilogram / u.metre**3)


# In[ ]:


uppercrust.radiogenicHeatProd = 1.5 * u.microwatt / u.meter**3
lowercrust.radiogenicHeatProd = 0.2 * u.microwatt / u.meter**3
mantleLithosphere.radiogenicHeatProd = 0.02e-6 * u.microwatt / u.meter**3


# In[ ]:


rh = GEO.ViscousCreepRegistry()


# In[ ]:


air.viscosity                = 1e19 * u.pascal * u.second
uppercrust.viscosity         = 1*rh.Wet_Quartz_Dislocation_Gleason_and_Tullis_1995
lowercrust.viscosity         = 1*rh.Dry_Mafic_Granulite_Dislocation_Wang_et_al_2012
mantleLithosphere.viscosity  = 1*rh.Dry_Olivine_Dislocation_Hirth_and_Kohlstedt_2003
mantle.viscosity             = 1*rh.Wet_Olivine_Dislocation_Hirth_and_Kohlstedt_2003


# In[ ]:


pl = GEO.PlasticityRegistry()


# In[ ]:


uppercrust.plasticity = GEO.DruckerPrager(name="uppercrust_plastic",
                                     cohesion=20. * u.megapascal,
                                     cohesionAfterSoftening=20. * u.megapascal,
                                     frictionCoefficient=0.6,
                                     frictionAfterSoftening=0.06,
                                     epsilon1=0.2, epsilon2=1.2)
lowercrust.plasticity = GEO.DruckerPrager(name="lowercrust_plastic",
                                     cohesion=20. * u.megapascal,
                                     cohesionAfterSoftening=20. * u.megapascal,
                                     frictionCoefficient=0.6,
                                     frictionAfterSoftening=0.06,
                                     epsilon1=0.2, epsilon2=1.2)
mantleLithosphere.plasticity = GEO.DruckerPrager(name="mantleLithosphere_plastic",
                                     cohesion=20. * u.megapascal,
                                     cohesionAfterSoftening=20. * u.megapascal,
                                     frictionCoefficient=0.6,
                                     frictionAfterSoftening=0.06,
                                     epsilon1=0.2, epsilon2=1.2)


# ## Temperature Boundary Condition

# In[ ]:


Model.set_temperatureBCs(top=293.15 * u.degK, 
                         bottom=1393.15 * u.degK, 
                         materials=[(mantle, 1393.15 * u.degK), (air, 293.15 * u.degK)])


# ## Velocity Boundary Conditions

# In[ ]:



Model.set_velocityBCs(left=[-0.64 * u.centimeter / u.year, 0., None],
                          right=[0.64 * u.centimeter / u.year, 0., None],
                          back=[None, 0., None],
                          front=[None, 0., None],
                          bottom=GEO.LecodeIsostasy(reference_mat=mantle),top=[None, None, None])






# In[ ]:


#plastic damage

import numpy as np

def gaussian(xx, centre, width):
    return ( np.exp( -(xx - centre)**2 / width ))

maxDamage = 0.7
Model.plasticStrain.data[:] = maxDamage * np.random.rand(*Model.plasticStrain.data.shape[:])
Model.plasticStrain.data[:,0] *= gaussian(Model.swarm.particleCoordinates.data[:,0], GEO.nd(0. * u.kilometer), GEO.nd(4.0 * u.kilometer))
Model.plasticStrain.data[:,0] *= gaussian(Model.swarm.particleCoordinates.data[:,1], (GEO.nd(Model.maxCoord[1] - Model.minCoord[1])) / 2.0, GEO.nd(8.0 * u.kilometer))
Model.plasticStrain.data[:,0] *= gaussian(Model.swarm.particleCoordinates.data[:,2], GEO.nd(-37. * u.kilometer) , GEO.nd(4.0 * u.kilometer))



# In[ ]:


#passive tracers

npoints = 512 # This is the number of points used to define the surface

xx = np.linspace(GEO.nd(Model.minCoord[0]), GEO.nd(Model.maxCoord[0]), npoints)
yy = np.linspace(GEO.nd(Model.minCoord[1]), GEO.nd(Model.maxCoord[1]), npoints)
zz = 0.

xx,yy,zz = np.meshgrid(xx,yy,zz)
coords = np.ndarray((xx.size, 3))

coords[:,0] = xx.ravel()
coords[:,1] = yy.ravel()
coords[:,2] = zz.ravel()
surface_tracers = Model.add_passive_tracers(name="Surface", vertices=coords)

coords[:,2] = GEO.nd(-20.*u.km)
BD_tracers = Model.add_passive_tracers(name="BD", vertices=coords)


coords[:,2] = GEO.nd(-35.*u.km)
moho_tracers = Model.add_passive_tracers(name="Moho", vertices=coords)


coords[:,2] = GEO.nd(-90.*u.km)
litho_tracers = Model.add_passive_tracers(name="Litho", vertices=coords)



# In[ ]:


Model.swarm.particleEscape=True


# In[ ]:


Model.init_model()


# In[ ]:


Model.solver.options.set_inner_method = "mg"


# In[ ]:


Model.solver.set_penalty(1e-5)


# In[ ]:


Model.run_for(20.0 * u.megayear, checkpoint_interval= 4.0 * u.megayear)
