### ISSUE TITLE
Checkpoint problem with latest UWgeodynamics on HPC cluster

### ISSUE THREAD

**Issue by HanyMKhalil** [underworldcode/UWGeodynamics#255]
Hi all, we were successfully installed the latest UWgeodynamics on SANAM HPC in Saudi Arabia however we have a weird problem. The code runs fine without checkpoint defined, yet when we define the checkpoint as follow:
Model.run_for(40.0 * u.megayear, checkpoint_interval=1. * u.megayear)

we get the following error:
Traceback (most recent call last):
  File "Harrat.py", line 529, in <module>
    Model.run_for(40.0 * u.megayear, checkpoint_interval=1. * u.megayear)
  File "/opt/venv/lib/python3.8/site-packages/UWGeodynamics/_model.py", line 1613, in run_for
    checkpointer = _CheckpointFunction(
  File "/opt/venv/lib/python3.8/site-packages/UWGeodynamics/_model.py", line 2335, in __init__
    self.checkpoint_all()
  File "/opt/venv/lib/python3.8/site-packages/UWGeodynamics/_model.py", line 2415, in checkpoint_all
    self.checkpoint_swarms(variables, checkpointID, time, outputDir)
  File "/opt/venv/lib/python3.8/site-packages/UWGeodynamics/_model.py", line 2566, in checkpoint_swarms
    string += _swarmvarschema(handle, field)
  File "/opt/venv/lib/python3.8/site-packages/underworld/utils/_utils.py", line 387, in _swarmvarschema
    h5f = h5py.File(name=varfilename, mode="r")
  File "/opt/venv/lib/python3.8/site-packages/h5py/_hl/files.py", line 444, in __init__
    fid = make_fid(name, mode, userblock_size,
  File "/opt/venv/lib/python3.8/site-packages/h5py/_hl/files.py", line 199, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 100, in h5py.h5f.open
OSError: Unable to open file (file signature not found)

**Comment by rbeucher** [comment]
@HanyMKhalil Do you still need help on this? I'm closing it now but feel free to re-open.
