### ISSUE TITLE
nodeSets not safe in parallel anymore

### ISSUE THREAD

**Issue by LukeMondy** [underworldcode/UWGeodynamics#83]
So I'm going through updating my model to match the changes in 1.0.0, and I've come across an issue where using nodeSets in boundary conditions is no longer parallel safe.

For example, I had this:
```python
air_mask = air_shape.fn.evaluate(Model.mesh.data)
air_nodes = Model.mesh.data_nodegId[air_mask].ravel()
astheno_mask = astheno_shape.fn.evaluate(Model.mesh.data)
astheno_nodes = Model.mesh.data_nodegId[astheno_mask].ravel()


# Temp initial conditions
Model.set_temperatureBCs(top=293.15 * u.degK, 
                         bottom=1603.15 * u.degK, 
                         nodeSets = [(air_mask, 293.15 * u.degK), (astheno_mask, 1603.15 * u.degK)])

```
On a single cpu, it's OK.
On more than 1, it says:
```
jovyan@7e4d8acb9a80:/host$ mpirun -np 2 python -u lmondy_rift.py 
loaded rc file /opt/UWGeodynamics/UWGeodynamics/uwgeo-data/uwgeodynamicsrc
	Global element size: 304x95
	Local offset of rank 0: 0x0
	Local range of rank 0: 152x95
In func WeightsCalculator_CalculateAll(): for swarm "I6XW1XSN__swarm"
	done 33% (4814 cells)...
	done 67% (9627 cells)...
	done 100% (14440 cells)...
WeightsCalculator_CalculateAll(): finished update of weights for swarm "I6XW1XSN__swarm"
Traceback (most recent call last):
  File "lmondy_rift.py", line 310, in <module>
Traceback (most recent call last):
  File "lmondy_rift.py", line 310, in <module>
    nodeSets = [(air_mask, 293.15 * u.degK), (astheno_mask, 1603.15 * u.degK)])
  File "/opt/UWGeodynamics/UWGeodynamics/_model.py", line 611, in set_temperatureBCs
    nodeSets = [(air_mask, 293.15 * u.degK), (astheno_mask, 1603.15 * u.degK)])
  File "/opt/UWGeodynamics/UWGeodynamics/_model.py", line 611, in set_temperatureBCs
An uncaught exception was encountered on processor 0.
An uncaught exception was encountered on processor 1.
    return self._temperatureBCs.get_conditions()
  File "/opt/UWGeodynamics/UWGeodynamics/_boundary_conditions.py", line 200, in get_conditions
    self._apply_conditions_nodes(condition, nodes)
  File "/opt/UWGeodynamics/UWGeodynamics/_boundary_conditions.py", line 163, in _apply_conditions_nodes
    return self._temperatureBCs.get_conditions()
  File "/opt/UWGeodynamics/UWGeodynamics/_boundary_conditions.py", line 200, in get_conditions
    self._apply_conditions_nodes(condition, nodes)
  File "/opt/UWGeodynamics/UWGeodynamics/_boundary_conditions.py", line 163, in _apply_conditions_nodes
    fromObject=nodes)
  File "/opt/underworld2/underworld/mesh/_mesh.py", line 1224, in __init__
    fromObject=nodes)
  File "/opt/underworld2/underworld/mesh/_mesh.py", line 1224, in __init__
    super(FeMesh_IndexSet,self).__init__(object,*args,**kwargs)
  File "/opt/underworld2/underworld/container/_indexset.py", line 599, in __init__
    super(FeMesh_IndexSet,self).__init__(object,*args,**kwargs)
  File "/opt/underworld2/underworld/container/_indexset.py", line 599, in __init__
    super(ObjectifiedIndexSet,self).__init__(*args,**kwargs)
  File "/opt/underworld2/underworld/container/_indexset.py", line 84, in __init__
    super(ObjectifiedIndexSet,self).__init__(*args,**kwargs)
  File "/opt/underworld2/underworld/container/_indexset.py", line 84, in __init__
    self.add(fromObject)
  File "/opt/underworld2/underworld/container/_indexset.py", line 132, in add
    self.add(fromObject)
  File "/opt/underworld2/underworld/container/_indexset.py", line 132, in add
    self._addremove(indices,True);
  File "/opt/underworld2/underworld/container/_indexset.py", line 177, in _addremove
    self._addremove(indices,True);
  File "/opt/underworld2/underworld/container/_indexset.py", line 177, in _addremove
    self._AddOrRemoveWithNumpyArray(indices, isadding)
    self._AddOrRemoveWithNumpyArray(indices, isadding)
  File "/opt/underworld2/underworld/container/_indexset.py", line 275, in _AddOrRemoveWithNumpyArray
  File "/opt/underworld2/underworld/container/_indexset.py", line 275, in _AddOrRemoveWithNumpyArray
    raise TypeError("Incompatible array type ({}) provided. Must be of integer type.".format(ndarray.dtype))
TypeError: Incompatible array type (bool) provided. Must be of integer type.
    raise TypeError("Incompatible array type ({}) provided. Must be of integer type.".format(ndarray.dtype))
TypeError: Incompatible array type (bool) provided. Must be of integer type.
--------------------------------------------------------------------------
MPI_ABORT was invoked on rank 1 in communicator MPI COMMUNICATOR 3 DUP FROM 0
with errorcode 1.

NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
You may or may not see output from other processes, depending on
exactly when Open MPI kills them.
--------------------------------------------------------------------------
^Cmpirun: abort is already in progress...hit ctrl-c again to forcibly terminate
```

I then tried using the newer method, as shown in: https://github.com/underworldcode/UWGeodynamics/blob/master/examples/1_25_Hot_Canon_Ball.ipynb
where you just pass a shape to the nodeSets. This also didn't work.
I then ran the Hot Canon Ball example in parallel, and see the same issue.

The original method used to be parallel safe, so I'm not sure what changed so that it is not.

Cheers,
Luke

**Comment by rbeucher** [comment]
Hi Luke,

Do you pass the mask or the nodes to the function?

**Comment by rbeucher** [comment]
OK I managed to reproduced the bug.. I am on it.

**Comment by rbeucher** [comment]
OK Luke, this f93fbfc should fix this.
Pass the shape directly to nodeSets:

```python
# Temp initial conditions
Model.set_temperatureBCs(top=293.15 * u.degK, 
                         bottom=1603.15 * u.degK, 
                         nodeSets = [(air_shape, 293.15 * u.degK), (astheno_shape, 1603.15 * u.degK)])
```

Note that the Shapes are not deformed when the model is running. So this can be used to initialized the temperature field but if you want to keep a material at some temperature it is better to use the materials option.

**Comment by rbeucher** [comment]
Is it OK now?
