### ISSUE TITLE
I need help for checking

### ISSUE THREAD

**Issue by cgw0814** [underworldcode/UWGeodynamics#95]
Hi, everyone, I tested the simple 3D programm,

the code as following attached
[simple-rift-3D-2019-0227.ipynb.tar.gz](https://github.com/underworldcode/UWGeodynamics/files/2909986/simple-rift-3D-2019-0227.ipynb.tar.gz)

I don't know what is means that screen showed massage 

`Running with UWGeodynamics version 2.7.1
Options:  -remove_constant_pressure_null_space False -ksp_k2_type NULL -change_backsolve False -pc_type none -force_correction True -Q22_pc_type gkgdiag -change_A11rhspresolve False -ksp_type bsscr -rescale_equations False -restore_K False -A11_pc_type lu -A11_pc_factor_mat_solver_package mumps -A11_ksp_type preonly -scr_ksp_type fgmres -scr_ksp_rtol 1e-05 -A11_mg_active False`

**Comment by cgw0814** [comment]
When I run the tutorial 9 in container

with `mpirun -np 4 python Tutorial_9_passive_margins.py`


the screen showed the erro massage

`Linear solver (28C35J3A__system-execute), solution time 4.255221e+00 (secs)
In func SystemLinearEquations_NonLinearExecute: Iteration 5 of 500 - Residual 0.0079219 - Tolerance = 0.01
Non linear solver - Residual 7.92189492e-03; Tolerance 1.0000e-02 - Converged - 4.061960e+01 (secs)

In func SystemLinearEquations_NonLinearExecute: Converged after 5 iterations.
An uncaught exception was encountered on processor 1.
Traceback (most recent call last):
  File "Tutorial_9_passive_margins.py", line 393, in <module>
    Model.run_for(3.0 * u.megayear, checkpoint_interval=0.1*u.megayear)
  File "/usr/local/lib/python2.7/dist-packages/pint/registry_helpers.py", line 216, in wrapper
    return func(*values, **kwargs)
  File "/opt/UWGeodynamics/UWGeodynamics/_model.py", line 1605, in run_for
    self._update()
  File "/opt/UWGeodynamics/UWGeodynamics/_model.py", line 1693, in _update
    self._advdiffSystem.integrate(dt)
  File "/opt/UWGeodynamics/UWGeodynamics/_model.py", line 801, in _advdiffSystem
    obj = uw.systems.SLCN_AdvectionDiffusion(
AttributeError: 'module' object has no attribute 'SLCN_AdvectionDiffusion'
An uncaught exception was encountered on processor 0.
application called MPI_Abort(comm=0x84000002, 1) - process 1
Traceback (most recent call last):
  File "Tutorial_9_passive_margins.py", line 393, in <module>
    Model.run_for(3.0 * u.megayear, checkpoint_interval=0.1*u.megayear)
  File "/usr/local/lib/python2.7/dist-packages/pint/registry_helpers.py", line 216, in wrapper
    return func(*values, **kwargs)
  File "/opt/UWGeodynamics/UWGeodynamics/_model.py", line 1605, in run_for
An uncaught exception was encountered on processor 2.
Traceback (most recent call last):
  File "Tutorial_9_passive_margins.py", line 393, in <module>
    Model.run_for(3.0 * u.megayear, checkpoint_interval=0.1*u.megayear)
  File "/usr/local/lib/python2.7/dist-packages/pint/registry_helpers.py", line 216, in wrapper
    return func(*values, **kwargs)
  File "/opt/UWGeodynamics/UWGeodynamics/_model.py", line 1605, in run_for
    self._update()
  File "/opt/UWGeodynamics/UWGeodynamics/_model.py", line 1693, in _update
    self._update()
  File "/opt/UWGeodynamics/UWGeodynamics/_model.py", line 1693, in _update
    self._advdiffSystem.integrate(dt)
  File "/opt/UWGeodynamics/UWGeodynamics/_model.py", line 801, in _advdiffSystem
    obj = uw.systems.SLCN_AdvectionDiffusion(
AttributeError: 'module' object has no attribute 'SLCN_AdvectionDiffusion'
An uncaught exception was encountered on processor 3.application called MPI_Abort(comm=0x84000004, 1) - process 0
    self._advdiffSystem.integrate(dt)
  File "/opt/UWGeodynamics/UWGeodynamics/_model.py", line 801, in _advdiffSystem

Traceback (most recent call last):
  File "Tutorial_9_passive_margins.py", line 393, in <module>
    obj = uw.systems.SLCN_AdvectionDiffusion(
    Model.run_for(3.0 * u.megayear, checkpoint_interval=0.1*u.megayear)
  File "/usr/local/lib/python2.7/dist-packages/pint/registry_helpers.py", line 216, in wrapper
AttributeError: 'module' object has no attribute 'SLCN_AdvectionDiffusion'
application called MPI_Abort(comm=0x84000002, 1) - process 2
    return func(*values, **kwargs)
  File "/opt/UWGeodynamics/UWGeodynamics/_model.py", line 1605, in run_for
    self._update()
  File "/opt/UWGeodynamics/UWGeodynamics/_model.py", line 1693, in _update
    self._advdiffSystem.integrate(dt)
  File "/opt/UWGeodynamics/UWGeodynamics/_model.py", line 801, in _advdiffSystem
    obj = uw.systems.SLCN_AdvectionDiffusion(
AttributeError: 'module' object has no attribute 'SLCN_AdvectionDiffusion'
application called MPI_Abort(comm=0x84000002, 1) - process 3`

**Comment by cgw0814** [comment]
When execte the Model_run in Tutorial_9_passive_margins.ipynb
also showed `Running with UWGeodynamics version 2.7.1
Options:  -remove_constant_pressure_null_space False -ksp_k2_type NULL -change_backsolve False -pc_type none -force_correction True -Q22_pc_type gkgdiag -change_A11rhspresolve False -ksp_type bsscr -rescale_equations False -restore_K False -A11_pc_type lu -A11_pc_factor_mat_solver_package mumps -A11_ksp_type preonly -scr_ksp_type fgmres -scr_ksp_rtol 1e-05 -A11_mg_active False`

and stop to output

**Comment by cgw0814** [comment]
I'm so sorry to disturb you@@"

**Comment by rbeucher** [comment]
No Worries!
So version 2.7.1 now outputs the options passed to the solver. Nothing to worry here. I have released the code last week and need to update the documentation. Sorry about that. 
Now the SLCN error:
remove the following line from tutorial 9:
```
GEO.rcParams["advection.diffusion.method"] = "SLCN"
```
That should work.

**Comment by cgw0814** [comment]
The result is the same without this command , I tried last night 0.0

**Comment by rbeucher** [comment]
If there is an error message it must be different.
